CREATE TABLE `primo-sito-web`.`DETTAGLIO_ORDINE` (
`Id` int AUTO_INCREMENT NOT NULL,
`IdOrdine` int NOT NULL,
`IdProdotto` int NOT NULL,
`PrezzoProdotto` DECIMAL(10,2) NOT NULL,
`Quantita` int NOT NULL,
PRIMARY KEY (`Id`),

CONSTRAINT FOREIGN KEY (`IdOrdine`)
REFERENCES `ORDINE` (`Id`)
ON DELETE RESTRICT ON UPDATE CASCADE,

CONSTRAINT FOREIGN KEY (`IdProdotto`)
REFERENCES `PRODOTTO` (`Id`)
ON DELETE RESTRICT ON UPDATE CASCADE
);