CREATE TABLE `primo-sito-web`.`PRODOTTO_FORNITORE` (
`IdProdotto` int NOT NULL,
`IdFornitore` int NOT NULL,
`Prezzo` int NOT NULL,
PRIMARY KEY (`IdProdotto`,`IdFornitore`),

CONSTRAINT FOREIGN KEY (`IdProdotto`) 
REFERENCES `PRODOTTO` (`Id`) 
ON DELETE RESTRICT ON UPDATE CASCADE,

CONSTRAINT FOREIGN KEY (`IdFornitore`)
REFERENCES `FORNITORE` (`Id`)
ON DELETE RESTRICT ON UPDATE CASCADE
)