CREATE TABLE `primo-sito-web`.`VISUALIZZAZIONE` (
`Email` varchar(45) NOT NULL,
`IdProdotto` int NOT NULL,
`Timestamp` datetime DEFAULT CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY (`Email`,`IdProdotto`,`Timestamp`),

CONSTRAINT FOREIGN KEY (`IdProdotto`)
REFERENCES `PRODOTTO` (`Id`) 
ON DELETE RESTRICT ON UPDATE CASCADE,

CONSTRAINT FOREIGN KEY (`Email`)
REFERENCES `UTENTE` (`Email`)
ON DELETE RESTRICT ON UPDATE CASCADE
)